# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a92f59af40c209d91ea7bd3278530e2b"
name = "TipTop360 Optimizer"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes ="read_products,write_products,read_themes,write_themes,read_content,write_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-04"
